FROM docker.io/bitnami/spark:2.4.6
#RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.704.jar
ADD spark-jars/* /opt/bitnami/spark/jars/